# Generated by Django 3.1.6 on 2021-02-28 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
