# Generated by Django 3.1.6 on 2021-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210228_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
