# Generated by Django 3.1.6 on 2021-02-28 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210228_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Lists'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Due to'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='mark',
            field=models.BooleanField(default=False, verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='owner',
            field=models.CharField(max_length=300, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=250, verbose_name='Tasks'),
        ),
    ]
