# Generated by Django 3.1.6 on 2021-03-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210228_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='owner',
            field=models.CharField(default='admin', max_length=300, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(blank=True, max_length=250, verbose_name='Tasks'),
        ),
    ]
